[pack]
name = "momentum"
version = "0.1.0"
description = "Document types for Momentum productivity app"
author = "Momentum Team"

[[types]]
name = "session"
description = "Active focus session state"
schema = "types/session.json"

[[types]]
name = "reflection"
description = "Post-session reflection document"
schema = "types/reflection.json"

[[types]]
name = "checklist"
description = "Pre-session checklist state"
schema = "types/checklist.json"
template = "templates/checklist.md"